# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Double Speech' do
  
  # Pods for Double Speech
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  use_frameworks!
  
  pod 'Starscream', '~> 3.0.2'
end
