# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Double Speech' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Double Speech
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '9.0'
  
  pod 'Starscream', '~> 3.0.2'

end
